= Hawkular WildFly Agent Installer
:source-language: java

== About

Hawkular WildFly Agent Installer is a standalone java application to install Hawkular WildFly Agent into a stock WildFly Server.

== Running Using Maven Command Line

Installer is configured via maven exec plugin so it installs Hawkular WildFly Agent from this repository into local WildFly located in `${org.hawkular.wildfly.home}`

    mvn exec:java -Dorg.hawkular.wildfly.home=/opt/wildfly-9.0.0.Final

== Running As Standalone Java Application

=== Building Standalone Jar

    mvn package

=== Running

Command line parameter `module-dist` is required unless installer retrieves Hawkular WildFly Agent module from `hawkular-server-url`

   java -jar target/hawkular-wildfly-agent-installer-0.10.1.Final-SNAPSHOT-standalone.jar \
     --module-dist=/path/to/module.zip \
     --target-location=/opt/wildfly-9.0.0.Final \
     --server-url=http://localhost:8080

Hawkular WildFly Agent is then installed to WildFly Server `/opt/wildfly-9.0.0.Final` as a module and is able to report to Hawkular Server located at `http://localhost:8080`.

== Using the Maven Plugin In Your .pom

If you have need to package an agent in your own WildFly distribution, you can do so using Maven with the following configuration:

[source,xml]
----
  <properties>
    <version.org.hawkular.agent>#.#.#</version.org.hawkular.agent>
    <wildfly.home>/the/location/of/your/wildfly/installation</wildfly.home>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.hawkular.agent</groupId>
      <artifactId>hawkular-wildfly-agent-wf-extension</artifactId>
      <type>zip</type>
      <version>${version.org.hawkular.agent}</version>
    </dependency>
  </dependencies>

  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-dependency-plugin</artifactId>
      <executions>
        <execution>
          <id>copy-hawkular-modules</id>
          <phase>prepare-package</phase>
          <goals>
            <goal>copy-dependencies</goal>
          </goals>
          <configuration>
            <outputDirectory>${project.build.directory}/hawkular-modules</outputDirectory>
            <includeArtifactIds>
              hawkular-wildfly-agent-wf-extension
            </includeArtifactIds>
            <stripVersion>true</stripVersion>
            <stripClassifier>true</stripClassifier>
            <overWriteIfNew>true</overWriteIfNew>
            <excludeTransitive>true</excludeTransitive>
          </configuration>
        </execution>
      </executions>
    </plugin>
    <plugin>
      <groupId>org.codehaus.mojo</groupId>
      <artifactId>exec-maven-plugin</artifactId>
      <executions>
        <execution>
          <id>install-agent-module</id>
          <phase>prepare-package</phase>
          <goals>
            <goal>java</goal>
          </goals>
          <configuration>
            <includePluginDependencies>true</includePluginDependencies>
            <mainClass>org.hawkular.wildfly.agent.installer.AgentInstaller</mainClass>
            <arguments>
              <argument>--target-location=${wildfly.home}</argument>
              <argument>--module=${project.build.directory}/hawkular-modules/hawkular-wildfly-agent-wf-extension.zip</argument>
              <argument>--server-url=http://localhost:8080</argument>
            </arguments>
          </configuration>
        </execution>
      </executions>
      <dependencies>
        <dependency>
          <groupId>org.hawkular.agent</groupId>
          <artifactId>hawkular-wildfly-agent-installer</artifactId>
          <version>${version.org.hawkular.agent}</version>
        </dependency>
        <dependency>
          <groupId>org.hawkular.agent</groupId>
          <artifactId>wildfly-module-installer</artifactId>
          <version>${version.org.hawkular.agent}</version>
        </dependency>
      </dependencies>
    </plugin>
  </plugins>
----

== Setting up SSL

If needed, the installer can setup a secured connection between the Hawkular WildFly Agent and the Hawkular server. By specifying `https` scheme  (ie. `--server-url=https://localhost:8443`) the following command-line options become required: `--keystore-path` and `--key-alias`. Installer also needs `--keystore-password` and `--key-password` options but they can be omitted in case you run it in console (in such case, installer will prompt for passwords). For more details see http://www.hawkular.org/hawkular-services/docs/installation-guide/secure-comm.html[Secure Communications].

== Configuration File

Aside from command line options, you can specify the installer configuration through a properties configuration file. https://github.com/hawkular/hawkular-agent/blob/master/hawkular-wildfly-agent-installer/src/main/resources/hawkular-wildfly-agent-installer.properties[An example is here]. You tell the installer about your configuration file via the command line option `--installer-config`.
