= Hawkular Java Agent

[link=https://travis-ci.org/hawkular/hawkular-agent]
image::https://travis-ci.org/hawkular/hawkular-agent.svg?branch=master[Build Status]

[TIP, caption='Synopsis']
====
Hawkular Java Agent can be used to manage WildFly or EAP applications servers as well as any Java application exposing JMX data.
====

== Installation

The agent runs as a JVM Java Agent. See link:hawkular-javaagent/README.adoc[].

== Configuration

The agent is configured with a yaml file. For an example, see link:hawkular-javaagent-wildfly-feature-pack/src/main/resources/featurepack/content/standalone/configuration/hawkular-javaagent-config.yaml[]

== Running

You attach the Hawkular Java Agent to your own application, so running your application runs the Hawkular Java Agent with it.

If you want to test the Hawkular Java Agent, you can run it standalone and just point it to a remote Java application to manage (you do this by addinga remote-dmr or remote-jmx managed server definition to its configuration file). You can run it like this:

```
java -Dhawkular.rest.user=jdoe -Dhawkular.rest.password=password -Dhawkular.rest.url=http://localhost:8080 -jar hawkular-javaagent/target/hawkular-javaagent-*-shaded.jar config=hawkular-javaagent-wildfly-feature-pack/src/main/resources/featurepack/content/standalone/configuration/hawkular-javaagent-config.yaml
```
