#
# Copyright 2015-2016 Red Hat, Inc. and/or its affiliates
# and other contributors as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM jboss/wildfly:10.0.0.Final

MAINTAINER Heiko W. Rupp <hrupp@redhat.com>

#ADD target/agent.jar /tmp/
ADD target/installer.jar /tmp/
ADD test-simple.war /opt/jboss/wildfly/domain/deployments/

ENV HAWKULAR_SERVER http://hawkular:8080
ENV HAWKULAR_USER jdoe
ENV HAWKULAR_PASSWORD password

EXPOSE 8080 9090

WORKDIR /tmp

RUN java -jar installer.jar --enabled true --server-url ${HAWKULAR_SERVER} \
  --module-dist classpath:hawkular-wildfly-agent-wf-extension.zip --username ${HAWKULAR_USER} \
  --target-config=/opt/jboss/wildfly/domain/configuration/host.xml \
  --password ${HAWKULAR_PASSWORD} --target-location /opt/jboss/wildfly


CMD /opt/jboss/wildfly/bin/domain.sh
