#
# Copyright 2015-2017 Red Hat, Inc. and/or its affiliates
# and other contributors as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM jboss/wildfly:10.1.0.Final

MAINTAINER Hawkular project <hawkular-dev@lists.jboss.org>

ADD target/hawkular-wildfly-agent-installer-full.jar /tmp/installer.jar
ADD src/main/resources/hawkular_wildfly_agent_setup.sh /tmp/hawkular_wildfly_agent_setup.sh
# ADD test-simple.war /opt/jboss/wildfly/standalone/deployments/
ADD src/main/resources/standalone.conf $JBOSS_HOME/bin

ADD src/main/resources/run_hawkular_wildfly_agent.sh /opt/hawkular/bin/run_hawkular_agent.sh

ENV HAWKULAR_SERVER_PROTOCOL http
ENV HAWKULAR_SERVER_ADDR hawkular
ENV HAWKULAR_SERVER_PORT 8080
ENV HAWKULAR_AGENT_USER=jdoe HAWKULAR_AGENT_PASSWORD=password
ENV HAWKULAR_IMMUTABLE=true
ENV JAVA_OPTS="-Xmx256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -XX:MaxMetaspaceSize=256m"

EXPOSE 8080 9090

WORKDIR /tmp

RUN source ./hawkular_wildfly_agent_setup.sh && \
    generate_empty_keystore && \
    run_hawkular_agent_standalone_install

USER root
RUN yum install --quiet -y openssl && \
    rm -rf /var/cache/yum && \
    chown -RH jboss:0 $JBOSS_HOME/standalone /opt/hawkular && \
    chmod -R ug+rw $JBOSS_HOME/standalone /opt/hawkular && \
    rm /tmp/installer.jar && \
    rm /tmp/hawkular_wildfly_agent_setup.sh

USER jboss

WORKDIR /opt
CMD /opt/hawkular/bin/run_hawkular_agent.sh "standalone"
