== SUMMARY

This command CLI utility allows you to send commands to the Hawkular Server over the https://github.com/hawkular/hawkular-commons/tree/master/hawkular-command-gateway/hawkular-command-gateway-api[Hawkular Command Gateway] websocket,
which in turn can forward the command to the agent.

It can be run on the command line like this:

```
java -jar hawkular-agent-command-cli-*.jar <options>
```

where options include things such as your credentials, the command you want to send along with its parameters,
as well as optional binary data.

An example command to deploy a WAR to a specific WildFly instance in inventory:

```
java -jar hawkular-agent-command-cli-*.jar \
   --server-url http://myhost:8080 \
   --username myuser \
   --password myPassword \
   --command DeployApplicationRequest \
   '-PresourcePath=/t;hawkular/f;c15f9426-734e-4ee6-82d3-7b0d82c41a6d/r;Local~~'
   -PdestinationFileName=hello-world.war
   --binary-data-file=/home/me/files/hello-world.war
```

Notice you can pass parameters to your command using the `-Pname=value` arguments. You can specify 0, 1, or more `-P` options.

You can also pass map parameters in your command using the `-Mname:key=value` arguments. You can also specify 0, 1, or more `-M` options. For example, suppose your command requires that you pass two maps - one called "values" and one called "options". Further suppose you want to pass a "values" map having entries of "color=blue" and "sound=beep" and the "options" map having a single entry of "debug=true". You can send those maps parameters like this:


```
   -Mvalues:color=blue -Mvalues:sound=beep -Moptions:debug=true
```

Refer to the https://github.com/hawkular/hawkular-commons/tree/master/hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema[Command Gateway JSON schemas] to know what commands can be passed (the command name is the name of the schema)
and what parameters those commands support.
